### ISSUE TITLE
Set Typeface 

### ISSUE THREAD

**Issue by ParhamAhmadi** [armcha/LuseenBottomNavigation#13]
@armcha
Thank for your great library and great work
Is it possible to add a method which can get or set the Typeface of Bottom Navigation Items? 
It would be greater than normal Typeface 
Thank you again
I'm waiting for your response

**Comment by armcha** [comment]
Hi @ParhamAhmadi now it possible

bottomNavigationView.setFont(Typeface.createFromAsset(getApplicationContext().getAssets(), "fonts/your_font.ttf"));
