### ISSUE TITLE
no setViewPager() method found

### ISSUE THREAD

**Issue by AhmedNMahran** [armcha/LuseenBottomNavigation#2]
The library is very awesome, but you mentioned that I can use it with view pager using a method **setViewPager()**. and this was not found

**Comment by armcha** [comment]
Already fixed, thanks for issue

**Comment by AhmedNMahran** [comment]
OK, but I've downloaded the latest version and didn't find it.
another thing (suggestion)
if you can put a method to set custom typeface for the tab text it would be great :)
