### ISSUE TITLE
Shadow of bottom bar covers actual content

### ISSUE THREAD

**Issue by amilcar-andrade** [armcha/LuseenBottomNavigation#4]
It seems that the view you are creating with the gradient as a background it is actually cutting the content. In your examples the shadow looks good because you do not have any content and the background is white. I would expect to see something like the attached image where the shadow it is on top of the content. 

![screenshot_20160329-100021-2](https://cloud.githubusercontent.com/assets/802308/14110619/3aec813a-f595-11e5-9fee-a14ec76cc9b4.png)

**Comment by armcha** [comment]
Hi, thanks for issue.
With scrolling content it looks good 

![default](https://cloud.githubusercontent.com/assets/15573237/14111719/dbcc3720-f5dc-11e5-978e-73d6a20bbc21.png)

With non scrolling content you can do something like this

``` xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="@dimen/bottom_navigation_height"
        android:src="@drawable/adrenalin" />

    <com.luseen.luseenbottomnavigation.BottomNavigation.BottomNavigationView
        android:id="@+id/bottomNavigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true" />
</RelativeLayout>
```

Result 

![2](https://cloud.githubusercontent.com/assets/15573237/14111796/2d731698-f5dd-11e5-9a33-cdbf06869baa.png)

**Comment by amilcar-andrade** [comment]
@armcha

**Comment by amilcar-andrade** [comment]
@armcha so did you change something?

**Comment by armcha** [comment]
@amilcar-andrade soon there will be also available 

``` java
 bottomNavigationView.disableShadow() 
```

option

**Comment by amilcar-andrade** [comment]
Cool, thanks!

**Comment by armcha** [comment]
@amilcar-andrade can i close issue?
