### ISSUE TITLE
How to set the font size

### ISSUE THREAD

**Issue by fg2q1q3q** [armcha/LuseenBottomNavigation#6]
When I use the simplified Chinese, the text font is so big, I want to customize the size of the text, what should I do

**Comment by armcha** [comment]
@fg2q1q3q   Thank you for feedback. I will make it customisable for the next version.

**Comment by fg2q1q3q** [comment]
thank you，when the next version publish,please tell me

**Comment by armcha** [comment]
@fg2q1q3q  Ok
