### ISSUE TITLE
How to set selected Tab manually?

### ISSUE THREAD

**Issue by chrjsorg** [armcha/LuseenBottomNavigation#7]
Hi,

is it possible to select the tab manually?
(Using 5 tabs which have activities/fragments behind, I need to set the selected tab manually after I switch to an activity.)

Cheers,
 Chris

**Comment by armcha** [comment]
@chrjsorg it will be available in next version

``` java
 bottomNavigationView.selectTab(3);
```

**Comment by chrjsorg** [comment]
Thanks. Do you have an ETA?

**Comment by armcha** [comment]
@chrjsorg  at tomorrow

**Comment by chrjsorg** [comment]
Please close the issue when its live (gradle), so I get a notification and can try it out right away. Thanks :)
