### ISSUE TITLE
Tabs being doubled on orientation change?

### ISSUE THREAD

**Issue by chrjsorg** [armcha/LuseenBottomNavigation#9]
Is it possible for you to reproduce this issue on your side? I'm not quite sure if its an issue on my side. I tried to set the bottomNavigationView to null before creating the tabs etc. but I still get this issue.

**Comment by armcha** [comment]
I will fix it as soon as posible. Thanks

**Comment by armcha** [comment]
@chrjsorg fixed  bottomNavigationView.willNotRecreate(true);
